templates:
  - name: "EasyAgent"
    component_order:
        - "perceive"
        - "plan"
        - "invoke"
        - "state"
        - "reflect"
    components:
      profile:
        plugin:
          EasyProfilePlugin:
            profile_data: "agent_profiles"
      state:
        plugin:
          EasyStatePlugin: {}
      plan:
        plugin:
          EasyPlanPlugin: {}
      invoke:
        plugin:
          EasyInvokePlugin: {}
      perceive:
        plugin:
          EasyPerceivePlugin: {}
      reflect:
        plugin:
          EasyReflectPlugin: {}