templates:
  - name: "EasyAgent"
    component_order:
        - "perceive"
        - "plan"
        - "invoke"
        - "state"
        - "reflect"
    components:
      profile:
        plugin:
          EasyProfilePlugin:
            adapters:  {}
            profile_data: "agent_profiles"
      state:
        plugin:
          EasyStatePlugin:
            adapters: {}
      plan:
        plugin:
          EasyPlanPlugin:
            adapters: {}
      invoke:
        plugin:
          EasyInvokePlugin:
            adapters: {}
      perceive:
        plugin:
          EasyPerceivePlugin:
            adapters: {}
      reflect:
        plugin:
          EasyReflectPlugin:
            adapters: {}