name: EasyEnvironment
components:
  relation:
    plugin:
      EasyRelationPlugin:
        adapters: {}
        relations: 'agents_relation'
  space:
    plugin:
      EasySpacePlugin:
        adapters: {}
        agents: 'map_agents'